{% set name = "atdict" %}
{% set version = "0.9.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 52fa9afbd80cd66baf20b8a8f22995ca7579f1255cbc22a66a38c2aa91fbb39c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - atdict

about:
  home: https://github.com/alphatwirl/atdict
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Attribute-access ordered dictionary
  description: |
    atdict is an attribute-access ordered dictionary. You can use a
    key name as an attribute to access the value of the dictionary for
    a key, for example, o.key_name rather than o['key_name']. Only a
    minimum set of methods are implemented so as to minimize the
    chances of name conflicts.
  dev_url: https://github.com/alphatwirl/atdict
  doc_url: https://github.com/alphatwirl/atdict#atdict

extra:
  recipe-maintainers:
    - TaiSakuma
