travis:
  secure:
    BINSTAR_TOKEN: ecqiVYCskwhv4EGuryL/bAWjxMD1IjIPyHSQFYdfFtNCPfeJbDVBYU8Duv3I4xni3VyDXype12Zh18fWbCyavz5bqquWVJqT+21/wBOC9LlE5gNi1uoIaa8CiHd/MhEe7IK8XI2NsVYHycDooDMjwJzmcZX7OLqUKflIkEm2rNEnyyp+XlDOrq5gk5VHQpgTLE4+iOI9BleHroFzYxy/S0k9VZv3rpkZVCWMn14Ek2mL2j/EFG8MrPhib8QznoXJfLP8Hf5x/ZxyQVOO67ud2GBhIrBdsr49ppQlGVki5WBbUO9rKJjScJzA969XsUOw6I12za/fvyEMFKwZD3ZIw7gJdrHvl7q63w+flG5xRENf0NLnCXC7k78MQ4lx/Y0fLrMU2hPLUAxebh/xzZBbLSJlLS/0WYyLnBvOoWhMKi7kIn96IRQKuOUqoxRlGnx5h8/M8kjkIDyh/5Qh+XwJzWNnzvsUr7nFKKiOdswwuFxls1ERvOxBhr7oomVgFxk5bJQPqeWMsupn5KozTK7Yvpn3UfGXsAtVRgApbwPlbjLO08X1GnSnEvVW7CkyLC7gp+kkNKtNQBqjsyxmZ0rUIBzvyMVrPMVf/JgNTLlTTePQbmExrcPeAIpouMd7LqjzQpE9VYRiiaS5kJkeTx14gyqKoHiXJ7srGyW3TCAVCA8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
